pipeline{
	agent any

	environment{
		IMAGE_NAME = "my-react-app"
		
	}

	stages{
		stage('Clone Code'){
			steps{
				git branch: 'main', url: 'https://github.com/PrinceKumar101/Devops.git'
				}
			}
		stage('Check Files'){
			steps{
				sh 'ls -la'
				}
			}
		stage('Build Image'){
			steps{
				sh 'docker build -t $IMAGE_NAME .'
				}
			}
		stage('Stop Old Container'){
			steps{
				sh 'docker stop react-container || true'
				}
			}

		stage('Remove Old Container'){
			steps{
				sh 'docker rm react-container || true'
				}
			}
		stage('Run New Container'){

			steps{
				sh 'docker run -d -p 3000:80 --name react-container $IMAGE_NAME'
				}
			}
		}
}
