pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-react-app"
    }

    stages {

        stage('Check Files') {
            steps {
                sh 'ls -la'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME aws_project/'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop react-container || true'
                sh 'docker rm react-container || true'
                sh 'docker run -d -p 3000:80 --name react-container $IMAGE_NAME'
            }
        }
    }
}
